### ISSUE TITLE
Video Quality

### ISSUE THREAD

**Issue by atul219** [udacimak/udacimak#97] opened 2020-03-30 08:24 UTC
Hi,

I am using this command
udacimak render "Directory" on hyper terminal 
and the videos are downloaded but the quality is not good.

So can you help me how to download high-quality video?

**Comment by udacimak** [comment] 2020-03-30 09:51
Duplicate of #87

**Comment by Kahol-g** [comment] 2020-03-30 17:15
Hey @atul219  
as a workaround you can  achieve this by making minor changes in the codebase 


first of all remove the fourth parameter in [here](https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js#L23)

`, format = '22/18/17'`

and make [argsYoutube an empty array](https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js#L50)

`  const argsYoutube = [];`

and run npm build from parent  directory you will get a lib directory created, and  traverse to lib in terminal   and use 

> **udacimak** download  nd-03

you should run 

> **node index.js** download nd-03  

and same for render

**Comment by MdTalhaZubayer** [comment] 2020-04-01 02:28
> Hey @atul219
> as a workaround you can achieve this by making minor changes in the codebase
> 
> first of all remove the fourth parameter in [here](https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js#L23)
> 
> `, format = '22/18/17'`
> 
> and make [argsYoutube an empty array](https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js#L50)
> 
> ` const argsYoutube = [];`
> 
> and run npm build from parent directory you will get a lib directory created, and traverse to lib in terminal and use
> 
> > **udacimak** download  nd-03
> 
> you should run
> 
> > **node index.js** download nd-03
> 
> and same for render

"Hey, I think it's for Linux/mac. Because it is not working on windows... please help me if its possible to do on windows

**Comment by MdTalhaZubayer** [comment] 2020-04-01 02:28
> Hey @atul219
> as a workaround you can achieve this by making minor changes in the codebase
> 
> first of all remove the fourth parameter in [here](https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js#L23)
> 
> `, format = '22/18/17'`
> 
> and make [argsYoutube an empty array](https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js#L50)
> 
> ` const argsYoutube = [];`
> 
> and run npm build from parent directory you will get a lib directory created, and traverse to lib in terminal and use
> 
> > **udacimak** download  nd-03
> 
> you should run
> 
> > **node index.js** download nd-03
> 
> and same for render

"Hey, I think it's for Linux/mac. Because it is not working on windows... please help me if it's possible to do on windows

**Comment by zhangchi0605** [comment] 2020-04-03 22:29
I still suffering of this quality problem, wenn could I expect to have a new version of udacimak that fix this problem? That would be great.

**Comment by zhangchi0605** [comment] 2020-04-03 22:31
> Hey @atul219
> as a workaround you can achieve this by making minor changes in the codebase
> 
> first of all remove the fourth parameter in [here](https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js#L23)
> 
> `, format = '22/18/17'`
> 
> and make [argsYoutube an empty array](https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js#L50)
> 
> ` const argsYoutube = [];`
> 
> and run npm build from parent directory you will get a lib directory created, and traverse to lib in terminal and use
> 
> > **udacimak** download  nd-03
> 
> you should run
> 
> > **node index.js** download nd-03
> 
> and same for render

Hi Could you explain a litte bit more, where can find the "codebase" and how can I "run npm build from parent directory "

**Comment by udacimak** [comment] 2020-04-07 10:20
Fixed in 2e467ee945592d434833580171e48b3233fd24ca

Please update your Udacimak

**Closed by udacimak** 2020-04-07 10:20 UTC
