### ISSUE TITLE
Getting [error]: ERROR: status code 500

### ISSUE THREAD

**Issue by MdTalhaZubayer** [udacimak/udacimak#105] opened 2020-04-01 02:53 UTC
After downloading some of the files I'm getting this error...

I'm using Windows 10..1909
and the node version is ...12.16.1

```
× Getting Youtube video id DDxsC03d_KU information
2020-04-01T02:48:13.707Z [error]: ERROR: status code 500
STACK: Error: status code 500
    at Request.response (C:\Users\mdt51\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:67:35)
    at Request.emit (events.js:311:20)
    at Request.onRequestResponse (C:\Users\mdt51\AppData\Roaming\npm\node_modules\udacimak\node_modules\request\request.js:1059:10)
    at ClientRequest.emit (events.js:311:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
```

there was a similar issue listed here https://github.com/udacimak/udacimak/issues/99#issuecomment-606593515

@GhaziXX is saying You just need to retype the command and re-render at the same location, it will skip all the downloaded files and complete the rest!

but this method is not working for me please help..

**Comment by goldenguy123** [comment] 2020-04-02 12:01
I have same issue
 plz fix

**Comment by atul219** [comment] 2020-04-02 15:06
I am getting this same issue.
Any solutions?

**Comment by EmreBayat** [comment] 2020-04-06 06:21
Could you pleasse auth token. I can download for you?.

**Comment by udacimak** [comment] 2020-04-07 10:17
@MdTalhaZubayer I just released an update for Udacimak. Can you please update and re-try to `render`?

**Comment by stefanheyer** [comment] 2020-04-07 13:20
I had the same error previously. Unfortunately updating hasn't resolved it yet.

**Comment by 1871vinayak** [comment] 2020-04-07 13:44
@MdTalhaZubayer 
You can try the latest update, i think it might fix the issue, as replied by @udacimak . 👍 
If it fails or the issue resists the send me the JSON files to sk20011999@gmail.com so that i can test it on my workspace for any issue..

@stefanheyer 
 Could you please send me the JSON files to sk20011999@gmail.com so that i can test it on my workspace for any issue..

**Comment by atul219** [comment] 2020-04-07 14:35
Still getting this same error after updating Udacimak.

**Comment by 1871vinayak** [comment] 2020-04-07 17:42
@atul219 
 Could you please send me the JSON files to sk20011999@gmail.com so that i can test it on my workspace for any issue..

**Comment by MdTalhaZubayer** [comment] 2020-04-07 17:46
> @atul219
> Could you please send me the JSON files to [sk20011999@gmail.com](mailto:sk20011999@gmail.com) so that i can test it on my workspace for any issue..

I have already sent those JSON files please check your mailbox bro

**Comment by abenacamp** [comment] 2020-04-07 23:00
@MdTalhaZubayer which particular course are  you have trouble downloading it

**Comment by MdTalhaZubayer** [comment] 2020-04-08 00:01
> @MdTalhaZubayer which particular course are you have trouble downloading it

Front End Developer, nd0011

**Comment by 1871vinayak** [comment] 2020-04-08 01:39
@MdTalhaZubayer 
I have tested it, and found the same issue, could you please re-download the JSON files and give it a try, i think there is an issue withe the JSON files, if not then its a problem with youtube-dl.
so please give it a try once.

**Comment by MdTalhaZubayer** [comment] 2020-04-08 01:51
> @MdTalhaZubayer
> I have tested it, and found the same issue, could you please re-download the JSON files and give it a try, i think there is an issue withe the JSON files, if not then its a problem with youtube-dl.
> so please give it a try once.

I have tried it several times

**Comment by 1871vinayak** [comment] 2020-04-08 01:53
@MdTalhaZubayer 
Wait i got it what the issue is, actually its an `Server side youtube error` Please give me some time so that i can fix it.

**Comment by udacimak** [comment] 2020-04-08 07:21
Thanks @1871vinayak for the pull request to fix this issue.

However, for some reason when I try rendering with the new code, the video quality goes down to 640x360. If I leave the `best[height=1080]` code in place, then the video quality will stay at 1280x720. Is this the same on your end?

I've reverted the `merge` of  your pull request. This issue will needs further inspection.

**Comment by atul219** [comment] 2020-04-08 07:52
@1871vinayak  Still getting the same error at the same exact module.

**Comment by udacimak** [comment] 2020-04-08 10:50
I have updated Udacimak and the issue should be fixed. Please update Udacimak and render the course again.

**Closed by udacimak** 2020-04-08 10:50 UTC

**Comment by 1871vinayak** [comment] 2020-04-08 11:38
> 
> 
> Thanks @1871vinayak for the pull request to fix this issue.
> 
> However, for some reason when I try rendering with the new code, the video quality goes down to 640x360. If I leave the `best[height=1080]` code in place, then the video quality will stay at 1280x720. Is this the same on your end?
> 
> I've reverted the `merge` of your pull request. This issue will needs further inspection.

@udacimak Yes i also tested for rendering new code and got the same error.
but with your latest update the quality is again goes down to 360p

**Comment by hantatsang** [comment] 2020-04-08 11:41
@1871vinayak could you please check again.

In this new version, if it can't download the 720p video, it will revert back to download 360p. So some videos might be 360p while (most) other videos will be 720p

**Comment by 1871vinayak** [comment] 2020-04-08 11:45
@atul219  Actually its an Server side youtube error which doesn't provide the resolution we are asking for which is [720p]. but provides [360p] instead , as @udacimak released an update with the fix that it will not throw any error but the download quality will be degraded to 360p, I suggest u to first try the latest update version to check for the results.

**Comment by 1871vinayak** [comment] 2020-04-08 11:48
> 
> 
> @1871vinayak could you please check again.
> 
> In this new version, if it can't download the 720p video, it will revert back to download 360p. So some videos might be 360p while (most) other videos will be 720p

Have you tested it ???

**Comment by 1871vinayak** [comment] 2020-04-08 11:49
Please send the results!!!
