### ISSUE TITLE
Getting a ERROR: status code 500 for a JS course I'm trying to download

### ISSUE THREAD

**Issue by abhiank** [udacimak/udacimak#79] opened 2020-02-15 16:41 UTC
Hi, thanks for this amazing project!

I'm trying to download this Udacity Course - https://www.udacity.com/course/intro-to-javascript--ud803, however the program is crashing and stopping trying to download the first video itself from youtube. 

Downloading the JSON structure worked perfectly, but in the render stage, when I executed this command - 
`udacimak render /Users/abhi/Desktop/Udacity\ JS/Intro\ to\ JavaScript\ v1.0.0 --targetdir /Users/abhi/Desktop/NEW\ JS 
`

I got this error - 
```
✖ Getting Youtube video id cWOCLHmFvWw information
2020-02-15T16:30:00.742Z [error]: ERROR: status code 500
STACK: Error: status code 500
    at Request.response (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:67:35)
    at Request.emit (events.js:200:13)
    at Request.onRequestResponse (/usr/local/lib/node_modules/udacimak/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:205:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:452:22)
    at TLSSocket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)

```

My theory is that the Chinese text in the video title might be crashing it. I tried downloading the video directly using the latest node-youtube-dl and it worked. Perhaps updating the youtube-dl dependency to the latest version will fix this.. 

Thanks

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Node version: v12.4.0
 - npm version: 6.13.7
 - Udacimak Version: v1.4.5
 - Browser: Chrome

**Course Information**
 - Nanodegree or Course name: Intro to JavaScript
 - Version: v1.0.0

**Comment by Abdullah-AlEyoni** [comment] 2020-02-15 18:32
Hi, the problem is can't find youtube id `cWOCLHmFvWw `. check #77

**Comment by abhiank** [comment] 2020-02-16 10:54
Thanks for the reply @Abdullah-AlEyoni. 

A couple of follow up questions - 
1. What is the solution to it not being able to find the youtube video even though it is present?
2. Couldn't understand what you meant in the linked issue - `edit the data.json file and change the video id 9PoZXr8dxFA to author id for example 1YnNLi_Dy5M.` Which one is the "author-id"? Is it the channel id?

Thanks.

**Comment by Abdullah-AlEyoni** [comment] 2020-02-16 11:01
1- my solution to the frist one is downloading it using 3ed party app  or website like like
2 - I meant `another` not `author` sorry  :)

```
              "id": 232954,
              "key": "2e521022-553b-48df-be29-391101ce79c2",
              "title": "Intro to Data Types",
              "semantic_type": "VideoAtom",
              "is_public": true,
              "instructor_notes": "",
              "video": {
                "youtube_id": "y9ch4F_JovU",
                "china_cdn_id": "y9ch4F_JovU.mp4"
```
change the you `youtube_id`

**Comment by abhiank** [comment] 2020-02-16 12:11
> my solution to the frist one is downloading it using 3ed party app or website like like

Ah right. I got that. But isn't there a solution to this problem? Perhaps the newer versions of node-youtube-dl does not give this error?..

> - I meant another not author sorry :)
Oh no problem :)

**Comment by stela** [comment] 2020-02-22 13:42
I too have the same problem, receiving HTTP status 500 errors on the nd-013 self driving car course's camera calibration lesson videos, several of them, so gave up manually replacing IDs with other working videos. I attempted to bump upgrade to `"youtube-dl": "^3.0.2"` however that didn't seem to have any effect. Instead I added another error-ignoring block, near the end of the downloadYoutube.js file:
```javascript
      } else if (message.includes('500')) {
        logger.error(`Youtube video with id ${videoId} returned HTTP Status 500, continuing...`);
        resolve(null);
      } else {
        reject(error);
      }
```

You can find my little hack is at https://github.com/stela/udacimak https://github.com/stela/udacimak/commit/c23016185d1d8752b809b8a000c740042a9a3459 in case anybody just wants to download courses without a few videos, but it would be better to somehow fix it properly instead, in case those videos really are downloadable. Feel free to merge/use that commit if anybody thinks it's useful.

**Comment by revelationnow** [comment] 2020-02-23 09:01
It appears that even using the browser, the best video format (format code 22) isn't downloadable. I forced udacimak to download format 18 and the failures seem to go away, albeit the video quality is poorer.

**Comment by abhiank** [comment] 2020-02-23 15:22
@stela, how can I use the code from your fork to execute Udacimak?

**Comment by stela** [comment] 2020-02-23 19:46
Basically use the instructions provided in https://github.com/udacimak/udacimak/blob/master/CONTRIBUTING.md and https://github.com/udacimak/udacimak/wiki/How-to-Use.
@abhiank  First, download or clone my fork linked previously.
The, e.g. for a Mac if you took the nd013 course (see listnd output if you don't know the code):
```sh
npm install
npm run-script build
udacimak --help
udacimak listnd
udacimak download -t ~/Documents/nd013-json/ nd013
udacimak render -t ~/Documents/Udacity-SDC-rendered/ -d 1 -s --userquizanswer ~/Documents/nd013-json/Self-Driving\ Car\ Engineer\ v1.0.0/
```
However, I believe @relevationnow's fix is much better, you will actually get a copy of the otherwise missing videos that way, try his repository instead! That fix ought to get merged into udacimak.

**Comment by abhiank** [comment] 2020-02-24 11:16
@stela, thanks for your response. I was trying to do this myself to try and see if latest youtube-dl version could solve it and was really struggling with it due to lack of node knowledge. However you already observed that that didn't do anything. 

@revelationnow Thanks, your code worked. 

It seems the problem is with youtube-dl itself. I've submitted an issue here 
https://github.com/przemyslawpluta/node-youtube-dl/issues/297

**Comment by mariusneamtu** [comment] 2020-03-01 07:09
You can resolve easily, edit your json files just like that:
"video": {
                "youtube_id": "y9ch4F_JovU.mp4"
                "china_cdn_id": ""

**Comment by mariusneamtu** [comment] 2020-03-01 07:09
You can resolve easily, edit your json files just like that:
"video": {
                "youtube_id": "y9ch4F_JovU.mp4"
                "china_cdn_id": ""

**Comment by Ghaleb-alnakhlani** [comment] 2020-03-16 10:35
@abhiank could you please share the details on how you have managed to solve this error
I am stuck on the same error?

**Comment by abhiank** [comment] 2020-03-18 09:47
@Ghaleb-alnakhlani, you just need to follow the steps mentioned by @stela in his comment after cloning @revelationnow's fork's code. If you have any specific question about any of the steps you can ask us.

**Comment by Ghaleb-alnakhlani** [comment] 2020-03-18 10:43
@abhiank i know how to clone @revelationnow code but after i do the cloning how do i run it.
I mean when i first downloaded the udacimak the orginal one i just installed it using "npm". So for the one i download how i run it.

**Comment by udacimak** [comment] 2020-03-24 07:14
Thanks, everyone. I'm going to release an update soon using @revelationnow 's solution.

**Closed** 2020-03-24 08:04 UTC
