### ISSUE TITLE
Fail to install udacimake on MacOS

### ISSUE THREAD

**Issue by jacky-ttt** [udacimak/udacimak#9] opened 2018-11-19 09:22 UTC
It fails to run `sudo npm install -g udacimak` to install udacimak on MacOS. Below error occurs. 
```
Jackys-MacBook-Pro:~ jackytsang$ sudo npm install -g udacimak
/usr/local/bin/udacimak -> /usr/local/lib/node_modules/udacimak/lib/index.js

> youtube-dl@1.12.2 postinstall /usr/local/lib/node_modules/udacimak/node_modules/youtube-dl
> node ./scripts/download.js

/usr/local/lib/node_modules/udacimak/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin'
    at Object.mkdirSync (fs.js:750:3)
    at Function.sync (/usr/local/lib/node_modules/udacimak/node_modules/mkdirp/index.js:71:13)
    at createBase (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/downloader.js:54:12)
    at downloader (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/downloader.js:67:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/scripts/download.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@1.12.2 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.12.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jackytsang/.npm/_logs/2018-11-19T09_15_42_224Z-debug.log
```
The error occurs at postinstall of youtube-dl. 

I am running on 
- Darwin 18.2.0 (Mojave v10.14.1)
- node v10.13.0
- npm  v6.4.1

**Comment by udacimak** [comment] 2018-11-19 09:30
Duplicate of #1

**Closed** 2018-11-19 10:14 UTC
Labels: good first issue
